### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by chris1312**
Added unit test runs on PHP8 and changed composer.json requirements accordingly.

What else should be done:
* migrate `laminas/laminas-console` commands to `laminas/laminas-cli` - like commands

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
@chris1312 Thanks a lot!

I see you had to bump the version to PHP 7.3+ because Laminas requires this. That is fine.

This repo only contains an integration with the console somewhat indirectly. But.. the libraries that depend on this one, do need it (for example SlmQueue/Doctrine). So we should do something with this.

I think we should remove the code related to console from this repo. And the implementing libraries may than decide how they handle this. 

Anyhow: both these things above warrant a new major release. @basz Agreed?

**Comment by basz** [comment]
Go for it!

**Comment by roelvanduijnhoven** [comment]
@chris1312 What subpackage do you use (SlmQueueDoctrine, ..)? And would you be willing to update that one also to make it compatible after we have released a new major version here?

**Comment by chris1312** [comment]
@roelvanduijnhoven Doctrine and RabbitMQ ones.

I'll try to work on that.

**Comment by chris1312** [comment]
Also, I just noticed that I defined some wrong constraint, opened another PR https://github.com/JouwWeb/SlmQueue/pull/240

**Pull request merged**
