### PR TITLE
Feature/update to php72

### PR DESCRIPTION
**Pull request by basz**
branched of on #225 

tooling PSR2 + PSR12
php72-74

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
@basz The PR was fairly big due to code styling. I looked over the commits, and have no input at this point. Looks good to merge!

I'll test the library myself after this one has been merged.

**Comment by basz** [comment]
> @basz The PR was fairly big due to code styling. I looked over the commits, and have no input at this point. Looks good to merge!

I know, sorry about that... :-)

I think the only real change was that due to return types the execute method of a Job now only return int or void. The annotations allowed for string, but really anything could be returned.

**Comment by roelvanduijnhoven** [comment]
@basz Feel free to merge!

> I think the only real change was that due to return types the execute method of a Job now only return int or void. The annotations allowed for string, but really anything could be returned.

Let's list that in CHANGELOG.md as deprecation: _Jobs that return anything other than an int or `null`, will fail in this new release_.

**Comment by basz** [comment]
I've created a release as **draft**. The CHANGELOG.md is unused.

**Pull request merged**
